theme: jekyll-theme-architect

title: Group Movement in a RTS game
descrition: I am a university student from UPC studing Videogame Design and Development and here is my research in how to move units in group in a RTS game. Hope you enjoy it :)
